name: bfnlibrary
description: BFN Library
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  firebase_auth: ^0.15.4
  firebase_messaging: ^6.0.9
  cloud_firestore: ^0.13.0+1
  intl: ^0.16.1
  shared_preferences: ^0.5.6+1
  dynamic_theme: 1.0.1
  flutter_dotenv: ^2.1.0
  google_fonts: ^0.3.5
  getflutter: ^1.0.3
  google_sign_in: ^4.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

